#pragma once

#ifndef GPUINFRA_H2D_SIZE_MULTIPLIER
#define GPUINFRA_H2D_SIZE_MULTIPLIER 1
#endif

#ifndef GPUINFRA_D2H_SIZE_MULTIPLIER
#define GPUINFRA_D2H_SIZE_MULTIPLIER 1
#endif

#ifndef GPUINFRA_COMPUTE_SIZE_MULTIPLIER
#define GPUINFRA_COMPUTE_SIZE_MULTIPLIER 3
#endif

#if GPUINFRA_H2D_SIZE_MULTIPLIER < 1
#error "GPUINFRA_H2D_SIZE_MULTIPLIER must be a positive integer"
#endif

#if GPUINFRA_D2H_SIZE_MULTIPLIER < 1
#error "GPUINFRA_D2H_SIZE_MULTIPLIER must be a positive integer"
#endif

#if GPUINFRA_COMPUTE_SIZE_MULTIPLIER < 1
#error "GPUINFRA_COMPUTE_SIZE_MULTIPLIER must be a positive integer"
#endif
